/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2020-10-23 06:28:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  \r\n");
      out.write("    <!-- ëê¸ css & ëê¸ ë¶í¸ì¤í¸ë©-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("    <!-- Main css -->\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"../../resources/css/main_dark_2.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"../../resources/css/main_reple_2.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"../../resources/css/main_default.css\">\r\n");
      out.write("    <!-- logo í°í¸ -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Lobster&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- ëëê³ ë í°í¸ -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700;800&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- í ê¸, ì¤ë¥´ë¥µ jQuery -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <title>:::::: Tongrami ::::::</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"header-contanier\">\r\n");
      out.write("        <div class=\"header-wrap\">\r\n");
      out.write("            <header class=\"head\">\r\n");
      out.write("                <div class=\"logo\"><a href=\"#\"><img src=\"../../resources/images/Tongrami LOGO.png\" alt=\"íµê·¸ë¼ë¯¸ë¡ê³ \"> Tongrami</a></div>\r\n");
      out.write("                           <!-- ê²ìê¸°ë¥ ìì -->\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("      <form action=\"newList\" method=\"post\">\r\n");
      out.write("         <input type=\"text\" name=\"postId\"  placeholder=\"아이디를 검색하세요\">\r\n");
      out.write("<!--          <input type=\"submit\" value=\"ê²ì\" class=\"glyphicon glyphicon-search\"> -->\r\n");
      out.write("         <button type=\"button\" value=\"ê²ì\" class=\"glyphicon glyphicon-search\"></button>\r\n");
      out.write("      </form>\r\n");
      out.write("   </div>\r\n");
      out.write("<!-- ê²ìê¸°ë¥ ë -->\r\n");
      out.write("                <!-- <input type=\"text\" value=\"ddfdf\"> -->\r\n");
      out.write("                <!-- íë²ê±° ìì -->\r\n");
      out.write("                <div class=\"menuicon-contaniner\">\r\n");
      out.write("                    <input type=\"checkbox\" id=\"menuicon\">\r\n");
      out.write("                    <label for=\"menuicon\">\r\n");
      out.write("                        <span></span>\r\n");
      out.write("                        <span></span>\r\n");
      out.write("                        <span></span>\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <div class=\"sidebar\">\r\n");
      out.write("                        <div class=\"menu-1\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <a href=\"/post/list\"><li>Home</li></a>\r\n");
      out.write("                                <a href=\"/member/select\"><li>My info</li></a>\r\n");
      out.write("                                <a href=\"/post/add\"><li>Post</li></a>\r\n");
      out.write("                                <a href=\"/\"><li>Logout</li></a>\r\n");
      out.write("                                <c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.memAuthor == 'ADMIN'}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                <a href=\"/member/list\"><li>Users</li></a>\r\n");
      out.write("                                </c:if>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <div class=\"checkbox-wrap\">\r\n");
      out.write("                                <input type=\"checkbox\" class=\"checkbox\" id=\"checkbox\">\r\n");
      out.write("                                <label for=\"checkbox\" class=\"label\">\r\n");
      out.write("                                    <div class=\"ball\"></div>\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- íë²ê±° ë -->\r\n");
      out.write("            </header>\r\n");
      out.write("        </div>\r\n");
      out.write(" \r\n");
      out.write("    </div> \r\n");
      out.write("    <!-- main ìë°ì¤í¬ë¦½í¸ -->  \r\n");
      out.write("    <script src=\"../../resources/js/main_toggle.js\"></script>\r\n");
      out.write("    <script src=\"../../resources/js/main_reple.js\"></script>\r\n");
      out.write("    <script src=\"../../resources/js/main_srr.js\"></script>\r\n");
      out.write("    <script src=\"../../resources/js/main_dark.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
